package com.tiffinbox.menu;

import java.io.PrintWriter;
import java.util.Comparator;
import java.util.List;
import java.util.Set;
import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.TypeElement;

/** Reads every @MenuItem while javac compiles, and writes one MenuCatalog.java. */
@SupportedAnnotationTypes("com.tiffinbox.menu.MenuItem")
@SupportedSourceVersion(SourceVersion.RELEASE_25)
public final class MenuCatalogProcessor extends AbstractProcessor {

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment round) {
        Set<? extends Element> dishes = round.getElementsAnnotatedWith(MenuItem.class);
        if (dishes.isEmpty()) return false;
        List<MenuItem> menu = dishes.stream()
                .map(e -> e.getAnnotation(MenuItem.class))
                .sorted(Comparator.comparing(MenuItem::name))
                .toList();
        try (PrintWriter out = new PrintWriter(processingEnv.getFiler()
                .createSourceFile("com.tiffinbox.MenuCatalog").openWriter())) {
            out.println("package com.tiffinbox;");
            out.println();
            out.println("import java.util.List;");
            out.println();
            out.println("/** GENERATED by MenuCatalogProcessor. Do not edit. */");
            out.println("public final class MenuCatalog {");
            out.println("    public static final List<String> ITEMS = List.of(");
            for (int i = 0; i < menu.size(); i++) {
                out.printf("            \"%s @ %d\"%s%n", menu.get(i).name(), menu.get(i).price(),
                        i == menu.size() - 1 ? ");" : ",");
            }
            out.println();
            out.println("    private MenuCatalog() {}");
            out.println();
            out.println("    public static int size() { return ITEMS.size(); }");
            out.println();
            out.println("    public static List<String> lines() { return ITEMS; }");
            out.println("}");
        } catch (Exception e) {
            throw new RuntimeException("could not write MenuCatalog.java", e);
        }
        return true;
    }
}
