plugins {
    java
}

group = "com.tiffinbox"
version = "1.0.0"

repositories { mavenCentral() }

dependencies { implementation("com.h2database:h2:2.5.250") }

tasks.withType<JavaCompile>().configureEach {
    options.release = 25
    options.encoding = "UTF-8"
}

// ---------------------------------------------------------------------------
// One custom task. It reads a text file and writes a Java source file.
//
// The three annotations are the whole subject of this unit. @InputFile and
// @OutputDirectory are not documentation: they are what Gradle hashes to decide
// whether this task has anything left to do. A task with no declared inputs has
// nothing to compare, so it can only ever be re-run or skipped for the wrong reason.
// ---------------------------------------------------------------------------
abstract class GenerateMenu : DefaultTask() {

    @get:InputFile
    abstract val menuFile: RegularFileProperty

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val items = menuFile.get().asFile.readLines().filter { it.isNotBlank() }
        val names = items.joinToString(", ") { "\"" + it.substringBefore('|') + "\"" }
        val pkg = outputDir.get().asFile.resolve("com/tiffinbox")
        pkg.mkdirs()
        pkg.resolve("MenuCatalog.java").writeText(
            """
            package com.tiffinbox;

            import java.util.List;

            /** Generated by the build from menu.txt. Do not edit. */
            public final class MenuCatalog {
                public static final List<String> ITEMS = List.of($names);
                public static int size() { return ITEMS.size(); }
                public static void main(String[] args) {
                    System.out.println("menu items: " + size());
                    System.out.println(ITEMS);
                }
            }
            """.trimIndent() + "\n")
    }
}

// Gradle 9.7.1 deprecates the `val x by tasks.registering(T::class)` delegate that most
// tutorials still use; it is scheduled for removal in Gradle 10. This is the form that stays.
val generateMenu = tasks.register<GenerateMenu>("generateMenu") {
    menuFile = layout.projectDirectory.file("src/main/menu/menu.txt")
    outputDir = layout.buildDirectory.dir("generated/menu")
}

// The generated directory becomes a source directory, so compileJava depends on
// generateMenu without anyone writing dependsOn: the wiring comes from the output.
sourceSets.main { java.srcDir(generateMenu) }
