// The SAME generator as the project one level up, with ONE annotation removed.
//
// There is no @InputFile here. The task still reads src/main/menu/menu.txt - it just
// reads it inside the action, from a plain File, where Gradle cannot see it. Gradle has
// an output to check and nothing to check it against, so after the first run the output
// exists and the task is declared up-to-date forever.
//
// Nothing about this is exotic. It is what every `File("...")` inside a task action does.

plugins { java }

group = "com.tiffinbox"
version = "1.0.0"

tasks.withType<JavaCompile>().configureEach {
    options.release = 25
    options.encoding = "UTF-8"
}

abstract class GenerateMenuUndeclared : DefaultTask() {

    // @get:InputFile  <- the line that is missing

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val f = File("src/main/menu/menu.txt")          // read behind Gradle's back
        val items = f.readLines().filter { it.isNotBlank() }
        val names = items.joinToString(", ") { "\"" + it.substringBefore('|') + "\"" }
        val pkg = outputDir.get().asFile.resolve("com/tiffinbox")
        pkg.mkdirs()
        pkg.resolve("MenuCatalog.java").writeText(
            """
            package com.tiffinbox;

            import java.util.List;

            /** Generated by the build from menu.txt. Do not edit. */
            public final class MenuCatalog {
                public static final List<String> ITEMS = List.of($names);
                public static int size() { return ITEMS.size(); }
                public static void main(String[] args) {
                    System.out.println("menu items: " + size());
                    System.out.println(ITEMS);
                }
            }
            """.trimIndent() + "\n")
    }
}

val generateMenu = tasks.register<GenerateMenuUndeclared>("generateMenu") {
    outputDir = layout.buildDirectory.dir("generated/menu")
}

sourceSets.main { java.srcDir(generateMenu) }
